Caching + geocoding + new themes
koenderks/rcityviews pull request #27
Opened 2024-10-14 14:40 UTC by pokyah

Hello @koenderks ,

I have implemented the following new functionalities : 

1. a caching mechanism using `memoise `package to alleviate calls to OSM servers and allowing to rebuild the same map with a new theme much faster. It does not change much the whole package. The magic happens thanks to a wrapper inside the exposed `cityview` function which has now 3 new params : `cache`, `persistent_cache `and `clear_cache`

2. a geocoding feature based on `tidygeocoder` package. If the city name is not found in the `rcityview` database, the `cityview` function will now attempt to geocode the name thanks to `tidygeocoder`. Implemented a new param  `method` in  `cityview`
 function to let the user choose the geocoding method provided to  `tidygeocoder`. Defaults to  `osm`.
 
3. have implemented new themes inspired from pyton prettymaps : https://github.com/marceloprates/prettymaps/tree/main. Added in the `helpers.R` script.

Let me know if something is unclear or need some adjustments. I'll be happy to contribute.

Best regards

2024-10-14 16:13 UTC, koenderks requested changes
Hi, 

From my first very short initial check, I noticed the following global stuff (see comments). If you could adjust that, then I can hopefully check out the code on a more detailed level somewhere next week. 

Additionally, it seems that the following code does not use the caching feature, do I misunderstand the intended workflow?
```
p <- rcityviews::cityview(name = "Hue", theme = "vintage")
p <- rcityviews::cityview(name = "Hue", theme = "original")
```

Finally, could you also run `roxygen2::roxygenize()` and `styler::style_package()` on the package?

2024-10-14 16:13 UTC, koenderks commented on .Rbuildignore
The changes to this file can be removed

2024-10-14 16:13 UTC, koenderks commented on R/builders.R
The additional spaces in this file can be removed

2024-10-14 16:13 UTC, koenderks commented on R/cityview.R
> +library(dplyr)
Please remove these library calls, see section 'Dependencies' at https://cran.r-project.org/web/packages/EpiForsk/vignettes/Writing_functions.html. Use `::` to call functions from a difference package.

2024-10-14 16:13 UTC, koenderks commented on R/cityview.R
> +  cache_dir <- file.path(path.expand("~"), "Documents", "cityview_cache")
Did you look into using a `tempdir()`? I'm not sure if that would work btw.

2024-10-14 16:13 UTC, koenderks commented on R/cityview.R
> +      memoise(.buildCity, cache = cache_filesystem(cache_dir))
See comment above, this should become`memoise::memoise`

2024-10-14 16:13 UTC, koenderks commented on R/helpers.R
> +
Extra line?

2024-10-14 16:13 UTC, koenderks commented on rcityviews.Rproj
This file can be removed from the PR

2024-10-14 16:13 UTC, koenderks commented on inst/fonts/LibreBaskerville-Regular.ttf
Should you add these fonts in the `onLoad()` function in the `zzz.R` file?

2024-10-14 16:13 UTC, koenderks commented on DESCRIPTION
Do we use `dplyr`, `httr` and `jsonlite` explicitly in the package (i.e., do they need to be imported, or are they dependencies of other packages)?

2024-10-14 21:52 UTC, koenderks commented
I think I have a working caching implementation on https://github.com/koenderks/rcityviews/pull/28, such that the following command does not require re-requesting the data from the overpass server. 
```
p <- cityview("Hue", theme = "original")
p <- cityview("Hue", theme = "rouge")
```
We could try to merge that first (if everything works) and then add your further changes like the themes after that step-by-step?

2024-10-15 12:57 UTC, pokyah commented
> I have implemented the caching implementation on #28, such that the following command does not require re-requesting the data from the overpass server.
> 
> ```
> p <- cityview("Hue", theme = "original")
> p <- cityview("Hue", theme = "rouge")
> ```
> 
> We can add your further changes like the geocoding, but it may be a better idea to rebase and make a new PR with that functionality. I would prefer to separate the individual components for version control, so its probably best to make a PR with only the geocoding functionality first.

Thanks for this ! I'll do the rebase and submit a new PR for the geocoding stuff

2024-10-15 14:50 UTC, closed without merging